var express = require("express");
var app = express();
var http = require("http");
// express is running over socket
var server = http.createServer(app);

var io = require("socket.io")(server);

var port = process.env.PORT || 3000;

// connection is the built in event generated by socket
io.on("connection", client => {
    console.log("Client connected!", client.id);
    // let server know, its connected
    client.emit("acknowledge", { message: "You are connected!" });

    client.on("msgToServer", (chattername, msg) => {
        console.log(chattername + " says : " + msg);
        client.broadcast.emit("serverMsg", chattername, msg);
        client.emit("serverMsg", 'Me', msg);
    });

    client.on("disconnect", ()=>{
        // push the all messages in array or any collection
        // Message to be saved in mongo
    })
})

app.get("/", (req, res) => {
    res.sendFile(__dirname + "/public/socket-client.html");
});

server.listen(port, () => {
    console.log("Socket server is running on 3000.");
})